name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Everything
        run: |
          # 1. Find where the project is
          PROJECT_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \; | head -n 1)
          cd $PROJECT_DIR
          
          # 2. Install and Run
          npm install
          npx playwright install --with-deps
          npx playwright test --reporter=html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Arlene-Test-Assessment-Report
          path: "**/playwright-report/"
          retention-days: 30